# Generated by Django 4.2 on 2025-07-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValiderCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('ville', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
                ('date_de_commande', models.DateTimeField(auto_now=True)),
                ('items', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['-date_de_commande'],
            },
        ),
    ]
