# Generated by Django 4.2 on 2025-07-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_validercommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validercommande',
            name='items',
            field=models.CharField(max_length=800),
        ),
    ]
