# Generated by Django 4.2 on 2025-07-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_alter_validercommande_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='validercommande',
            name='total',
            field=models.CharField(default='500', max_length=200),
            preserve_default=False,
        ),
    ]
