# Generated by Django 4.2 on 2025-07-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_validercommande_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='validercommande',
            name='sous_qte',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
