# Generated by Django 4.2 on 2025-07-16 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_validercommande_sous_qte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validercommande',
            name='sous_qte',
        ),
    ]
